apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: chronos-*
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
      logMessageField: message
      logLevelField: level

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST

  - name: Redis
    type: redis
    access: proxy
    url: redis://redis:6379
    jsonData:
      pool: 0
      timeout: 10

  - name: Neo4j
    type: neo4j
    access: proxy
    url: http://neo4j:7474
    jsonData:
      database: neo4j
